steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker Image
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/sylvan-hydra-464904-d9/vamsi-trivy-flask-repo/flask-app:$SHORT_SHA',
        '.'
      ]

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push Image
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/sylvan-hydra-464904-d9/vamsi-trivy-flask-repo/flask-app:$SHORT_SHA'
      ]

  # Step 3: Pull image (simulate VM)
  - name: 'gcr.io/cloud-builders/docker'
    id: Pull for Test
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull us-central1-docker.pkg.dev/sylvan-hydra-464904-d9/vamsi-trivy-flask-repo/flask-app:$SHORT_SHA

  # Step 4: Run Trivy scan
  - name: 'aquasec/trivy:0.44.0'
    id: Trivy Scan
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        trivy image \
          --scanners vuln \
          --format table \
          --exit-code 0 \
          --output /workspace/trivy-report.txt \
          us-central1-docker.pkg.dev/sylvan-hydra-464904-d9/vamsi-trivy-flask-repo/flask-app:$SHORT_SHA

  # Step 5: Upload report to GCS
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Upload Report
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TIMESTAMP=$$(date +%Y%m%d-%H%M%S)
        gsutil cp /workspace/trivy-report.txt gs://vamsi-trivy-reports/trivy-report-$$TIMESTAMP.txt

  # ✅ Step 6: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy to Cloud Run
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy flask-trivy-app \
          --image=us-central1-docker.pkg.dev/sylvan-hydra-464904-d9/vamsi-trivy-flask-repo/flask-app:$SHORT_SHA \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --port=8080 \
          --service-account=57920515119-compute@developer.gserviceaccount.com

timeout: 5400s

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 57920515119-compute@developer.gserviceaccount.com
