steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker Image
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/sylvan-hydra-464904-d9/vamsi-trivy-flask-repo/flask-app:$SHORT_SHA',
        '.'
      ]

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push Image
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/sylvan-hydra-464904-d9/vamsi-trivy-flask-repo/flask-app:$SHORT_SHA'
      ]

  # Step 3: Pull image (simulate VM)
  - name: 'gcr.io/cloud-builders/docker'
    id: Pull for Test
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull us-central1-docker.pkg.dev/sylvan-hydra-464904-d9/vamsi-trivy-flask-repo/flask-app:$SHORT_SHA



  # ✅ Step 6: Deploy to Cloud Run (with port 5000)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy to Cloud Run
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy flask-trivy-app \
          --image=us-central1-docker.pkg.dev/sylvan-hydra-464904-d9/vamsi-trivy-flask-repo/flask-app:$SHORT_SHA \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --port=5000 \
          --service-account=57920515119-compute@developer.gserviceaccount.com

timeout: 5400s

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 57920515119-compute@developer.gserviceaccount.com
