steps:
  # Step 1: Get the latest image digest
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Get-Latest-Digest
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Fetching latest image digest..."
        DIGEST=$$(gcloud artifacts docker images list us-central1-docker.pkg.dev/sylvan-hydra-464904-d9/vamsi-trivy-flask-repo/flask-app \
          --sort-by=UPDATE_TIME \
          --limit=1 \
          --format='value(DIGEST)')

        if [ -z "$$DIGEST" ]; then
          echo "❌ Failed to get latest digest"
          exit 1
        fi

        echo "LATEST_DIGEST=$${DIGEST}" > /workspace/digest.env
        echo "✅ Latest digest: $${DIGEST}"

  # Step 2: Pull the image using digest
  - name: gcr.io/cloud-builders/docker
    id: Pull-Image-Digest
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/digest.env
        echo "Pulling image with digest: $${LATEST_DIGEST}"
        docker pull us-central1-docker.pkg.dev/sylvan-hydra-464904-d9/vamsi-trivy-flask-repo/flask-app@$${LATEST_DIGEST}

  # Step 3: Deploy to Cloud Run using digest
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy-Cloud-Run
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/digest.env
        echo "Deploying to Cloud Run using digest..."
        gcloud run deploy flask-app-service \
          --image=us-central1-docker.pkg.dev/sylvan-hydra-464904-d9/vamsi-trivy-flask-repo/flask-app@${LATEST_DIGEST} \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --port=6000

options:
  logging: CLOUD_LOGGING_ONLY
