steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker Image
    args:
      [
        'build',
        '-t',
        'asia-south1-docker.pkg.dev/sylvan-hydra-464904-d9/vamsi-trivy-flask-repo/flask-app:$SHORT_SHA',
        '.'
      ]

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push Image
    args:
      [
        'push',
        'asia-south1-docker.pkg.dev/sylvan-hydra-464904-d9/vamsi-trivy-flask-repo/flask-app:$SHORT_SHA'
      ]

  # Step 3: Pull image (simulate VM)
  - name: 'gcr.io/cloud-builders/docker'
    id: Pull for Test
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull asia-south1-docker.pkg.dev/sylvan-hydra-464904-d9/vamsi-trivy-flask-repo/flask-app:$SHORT_SHA

  # ✅ Step 4: Deploy to Cloud Run with Secret Environment Variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy to Cloud Run
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy flask-trivy-app \
          --image=asia-south1-docker.pkg.dev/sylvan-hydra-464904-d9/vamsi-trivy-flask-repo/flask-app:$SHORT_SHA \
          --region=asia-south1 \
          --platform=managed \
          --allow-unauthenticated \
          --port=5000 \
          --service-account=awssecretkey@sylvan-hydra-464904-d9.iam.gserviceaccount.com \
          --set-secrets=AWS_ACCESS_KEY=projects/sylvan-hydra-464904-d9/secrets/AWS_ACCESS_KEY:1 \
          --set-secrets=AWS_SECRET_KEY=projects/sylvan-hydra-464904-d9/secrets/AWS_SECRET_KEY:1

timeout: 5400s

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: awssecretkey@sylvan-hydra-464904-d9.iam.gserviceaccount.com
